#pragma once

#ifndef ERRORCODES_H
#define ERRORCODES_H

enum IdolSchemeErrorCodes {
	BUTTON_INVALID = 199,
	NOTE_BADTYPE,
	NOTE_INVALID,
	NOTE_TIMEROFF,
	CONDUCTOR_OFF,
	CONDUCTOR_FETCHTIMEFAIL,
	GAME_LOAD_SCRIPT,
	GAME_LOAD_BACKGROUND,
	GAME_LOAD_BEATMAP,
	GAME_LOAD_SONG,
	GAME_LOAD_MENU,
	GAME_SAVE_SETTINGS,
};

#endif //!ERRORCODES_H